title: "FINDS Lab"
description: "Financial Data Intelligence & Solutions Lab."

# GitHub Pages 기본 도메인
url: "https://finds-lab.github.io"

# 프로젝트 페이지라서 저장소명 필요
baseurl: "/website"

# (선택) 테마 미사용 시 주석 처리 유지
# theme: minima

# 컬렉션 설정
collections:
  news:
    output: true
    permalink: /news/:name.html

# 기본 레이아웃/값 설정
defaults:
  - scope:
      path: ""
      type: news
    values:
      layout: news_post   # 개별 뉴스 페이지 기본 레이아웃

  - scope:
      path: "assets/docs"
    values:
      pdf: true

# Include docs folder
include:
  - assets/docs

# --- Open Graph / SEO (전역) ---
# 사이트 전역에서 사용할 기본 OG 이미지 (페이지가 별도 지정 안 했을 때 사용)
og_image: "/assets/img/thumbnail/findslab-thumbnail.png"

# jekyll-seo-tag 플러그인을 쓴다면 image 키도 인식됩니다 (선택)
image: "/assets/img/thumbnail/findslab-thumbnail.png"

# (선택) Twitter 계정
# twitter:
#   username: finds_lab

# 정적 자산/썸네일 캐시 버전(바꿀 때만 값 갱신)
asset_version: "20250919"

# (선택) SEO 플러그인 사용 시 주석 해제
# plugins:
#   - jekyll-seo-tag
